#!/bin/bash
# i execute this in the terminal to run the servers, you might find it handy for testing
if [[ "x$1" == "x" ]]
then
    "$0" centralserver &
    "$0" server
else
    cd "`dirname $0`"
    cd "./$1"
    while true; do
        node .
    done
fi
