#!/bin/bash
# i execute this in the terminal to run the servers, you might find it handy for testing
if [[ "x$1" == "x" ]]
then
    "$0" centralserver &
    while true; do
        "$0" server
    done
else
    cd "`dirname $0`"
    cd "./$1"
    node .
fi
